---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# rubintools

<!-- badges: start -->
<!-- badges: end -->

rubintools is a personal collection of helper functions.

## Installation

You can install the development version of rubintools like so:

```r
# install.packages("devtools")
devtools::install_github("Jean-Rubin/rubintools")
```

## Example

Here are some example of functions you can use

### Memory usage

```{r example-memory}
library(rubintools)
x <- 1:20
y <- list(a = x)
z <- rep(x, 4)

memory_ls()

memory_total()
```


### Data table manipulation

```{r example-data-table}
dt_example <- data.table::data.table(
  x = c(1, 1, 1, 1, 2, 2, 2, 2),
  y = c(1, 2, 3, 4, 5, 6, 7, 8),
  g = c("a", "a", "a", "a", "b", "b", "b", "b"),
  w = c("c", "c", "d", "d", "c", "c", "d", "d")
)
print(dt_example)

dt_tidy <- dt_tidy_statistics(dt_example, c("x", "y"), c("g", "w"), list("mean" = mean))
print(dt_tidy)
```


### Formatting number

```{r example-fmt-signif}
fmt_signif(21.35, 3)

fmt_signif(1.3, 3)
```


### Factor manipulation

```{r example-factor}
factor_as_numeric(factor(c("3", "1", "10")))

create_factor(
 "a" = "A",
 "b" = "B"
)
```


### Data dictionnary and labels

```{r example-label}
dict <- list(
  x = c("a" = "A", "b" = "B", "c" = "C"),
  y = c("d" = "D", "e" = "E", "f" = "F")
)
df_ex <- data.frame(
  x = c("a", "b"),
  y = c("d", "e")
)
recode_from_dict(df_ex, dict)
```

